### ISSUE TITLE
Definie address type in reverse geocoding?

### ISSUE THREAD

**Issue by adlondon** [marlove/react-native-geocoding#10]
Thanks for the super simple, easy to use package. Is there any way to define the address type when doing a reverse geocoding request? In particular I'm hoping to get a `street_address`

See: https://developers.google.com/maps/documentation/javascript/geocoding#GeocodingAddressTypes

**Comment by yairopro** [comment]
The `types[]` field you point in your link is in the response object, not to add in a request.
The geocoding api will give you all types available in the response for the result places.
