### ISSUE TITLE
Geocoder - "You have exceeded your daily request" but i just made 1 request ?!

### ISSUE THREAD

**Issue by mayon7** [marlove/react-native-geocoding#17]
Hi !
I have a problem, when I want to have a location there is this message : " You have exceeded your daily request" but i have just made 1 request ?
I don't understand ...
Thanks for help

**Comment by GeraldHeng** [comment]
I also had this problem and i found out that the problem lie with Google limiting our request to 1! To change this add a billing address to your google api account :)
