### ISSUE TITLE
Error while geocoding

### ISSUE THREAD

**Issue by mdelclaro** [marlove/react-native-geocoding#19]
It was working, but now I'm receiving this error:

`message: Error from the server while geocoding. The received datas are in the error's 'origin' field. Check it for more informations.`

```JSON
  code: 4
  origin:Object 
    plus_code:Object 
      global_code:"4CW22222+22"
  results:Array(0) 
    length:0
  status:"ZERO_RESULTS"
```

Perhaps it's an error on Google's side?

**Comment by mdelclaro** [comment]
5 seconds after submiting this issue (I've been trying to figure it out for almost 2 hours) I realized that the emulator had some random stupid coords that were actually in the middle of the ocean... lol

No problems at all. I apologize.

**Comment by darvinhuangg** [comment]
Hi @mdelclaro 
How do you solve this? 
I'm running in my iOS phone and also end up in the middle of ocean, but the code itself is working in Android.

**Comment by mdelclaro-gettyio** [comment]
@darvinhuangg are you running on the emulator or a physical device? I was running on the Android Studio emulator and there you can change the device's location. I'm not sure about iOS, sorry...

**Comment by mdelclaro** [comment]
@darvinhuangg are you running on the emulator or a physical device? I was running on the Android Studio emulator and there you can change the device's location. I'm not sure about iOS, sorry...

**Comment by darvinhuangg** [comment]
I'm running both platform on physical device. I've also checked the location in my iOS phone using maps and it gets exact coordinate location.
