### ISSUE TITLE
Is there a way to set language of returned address?

### ISSUE THREAD

**Issue by rendomnet** [marlove/react-native-geocoding#4]

**Comment by Johnstedt** [comment]
I've added a pull request to explicitly set the language a while ago but this repository seems inactive. You could checkout my PR or fork of the repository for a quick fix while waiting for the PR to go through. If you have not already found another solution.

**Comment by marlove** [comment]
@Johnstedt thank you for your contribution. Can you please solve the pending conflicts? I'd be very happy to merge the language support then.

**Comment by yairopro** [comment]
@Johnstedt You can close this issue now since #11 merged.

**Comment by nostagy8** [comment]
Solution,please

**Comment by yairopro** [comment]
@nostagy8 Read the exemple in the README.

**Comment by marlove** [comment]
It should be possible by passing the language as described below
`Geocoder.init("xxxxxxxxxxxxxxxxxxxxxxxxx", {language : "en"});`
